- name: install apache and php packages (Fedora)
  tags: apache,fedora,httpd
  dnf:
    name:
      - httpd
      - php
    state: latest
    update_cache: yes
  when: ansible_distribution == "Fedora"


- name: start and enable apache service
  tags: apache,httpd
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_distribution == "Fedora"


- name: change e-mail address for admin
  tags: apache,fedora,httpd
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin somebody@somewhere.com
  when: ansible_distribution == "Fedora"
  register: httpd


- name: copy html file for site
  tags: apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
